spring.application.name=Federation
spring.datasource.url=jdbc:postgresql://localhost:5432/federation
spring.datasource.username=postgres
spring.datasource.password=Alpha 263035
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
server.port=8081
